package com.liangduo.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLLECTION".
 */
public class Collection {

    private Long id;
    private String imageUrl;
    private String title;
    private String name;
    private String date;
    private String tag;
    private String feedId;

    public Collection() {
    }

    public Collection(Long id) {
        this.id = id;
    }

    public Collection(String imageUrl, String title, String name, String date, String tag, String feedId) {
        this.imageUrl = imageUrl;
        this.title = title;
        this.name = name;
        this.date = date;
        this.tag = tag;
        this.feedId = feedId;
    }

    public Collection(Long id, String imageUrl, String title, String name, String date, String tag, String feedId) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.title = title;
        this.name = name;
        this.date = date;
        this.tag = tag;
        this.feedId = feedId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getFeedId() {
        return feedId;
    }

    public void setFeedId(String feedId) {
        this.feedId = feedId;
    }

}
