package com.liangduo.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String number;
    private String psw;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String number, String psw) {
        this.id = id;
        this.number = number;
        this.psw = psw;
    }

    public User(String number, String psw) {
        this.number = number;
        this.psw = psw;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getPsw() {
        return psw;
    }

    public void setPsw(String psw) {
        this.psw = psw;
    }

}
